// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.0
// source: data_forwarding.proto

package forwarding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Angle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pitch float32 `protobuf:"fixed32,1,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Yaw   float32 `protobuf:"fixed32,2,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Roll  float32 `protobuf:"fixed32,3,opt,name=roll,proto3" json:"roll,omitempty"`
}

func (x *Angle) Reset() {
	*x = Angle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_forwarding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Angle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Angle) ProtoMessage() {}

func (x *Angle) ProtoReflect() protoreflect.Message {
	mi := &file_data_forwarding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Angle.ProtoReflect.Descriptor instead.
func (*Angle) Descriptor() ([]byte, []int) {
	return file_data_forwarding_proto_rawDescGZIP(), []int{0}
}

func (x *Angle) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *Angle) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *Angle) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

type BBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W int64 `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H int64 `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *BBox) Reset() {
	*x = BBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_forwarding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_data_forwarding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_data_forwarding_proto_rawDescGZIP(), []int{1}
}

func (x *BBox) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BBox) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BBox) GetW() int64 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BBox) GetH() int64 {
	if x != nil {
		return x.H
	}
	return 0
}

type Keypoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Keypoint) Reset() {
	*x = Keypoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_forwarding_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keypoint) ProtoMessage() {}

func (x *Keypoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_forwarding_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keypoint.ProtoReflect.Descriptor instead.
func (*Keypoint) Descriptor() ([]byte, []int) {
	return file_data_forwarding_proto_rawDescGZIP(), []int{2}
}

func (x *Keypoint) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Keypoint) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Face struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bbox       *BBox       `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	HasHP      bool        `protobuf:"varint,2,opt,name=hasHP,proto3" json:"hasHP,omitempty"`
	Timestamp  int64       `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pose       *Angle      `protobuf:"bytes,4,opt,name=pose,proto3" json:"pose,omitempty"`
	Embedding  []float32   `protobuf:"fixed32,5,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TrackId    int64       `protobuf:"varint,6,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	PersonId   string      `protobuf:"bytes,7,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Keypoints  []*Keypoint `protobuf:"bytes,8,rep,name=keypoints,proto3" json:"keypoints,omitempty"`
	Similarity float32     `protobuf:"fixed32,9,opt,name=similarity,proto3" json:"similarity,omitempty"`
	Thumbnail  string      `protobuf:"bytes,10,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
}

func (x *Face) Reset() {
	*x = Face{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_forwarding_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Face) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Face) ProtoMessage() {}

func (x *Face) ProtoReflect() protoreflect.Message {
	mi := &file_data_forwarding_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Face.ProtoReflect.Descriptor instead.
func (*Face) Descriptor() ([]byte, []int) {
	return file_data_forwarding_proto_rawDescGZIP(), []int{3}
}

func (x *Face) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Face) GetHasHP() bool {
	if x != nil {
		return x.HasHP
	}
	return false
}

func (x *Face) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Face) GetPose() *Angle {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *Face) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Face) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *Face) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *Face) GetKeypoints() []*Keypoint {
	if x != nil {
		return x.Keypoints
	}
	return nil
}

func (x *Face) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *Face) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type DataForwarding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte  `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Faces []*Face `protobuf:"bytes,2,rep,name=faces,proto3" json:"faces,omitempty"`
	Id    int32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Prime string  `protobuf:"bytes,4,opt,name=prime,proto3" json:"prime,omitempty"`
}

func (x *DataForwarding) Reset() {
	*x = DataForwarding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_forwarding_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataForwarding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataForwarding) ProtoMessage() {}

func (x *DataForwarding) ProtoReflect() protoreflect.Message {
	mi := &file_data_forwarding_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataForwarding.ProtoReflect.Descriptor instead.
func (*DataForwarding) Descriptor() ([]byte, []int) {
	return file_data_forwarding_proto_rawDescGZIP(), []int{4}
}

func (x *DataForwarding) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *DataForwarding) GetFaces() []*Face {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *DataForwarding) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataForwarding) GetPrime() string {
	if x != nil {
		return x.Prime
	}
	return ""
}

type DataForwardingStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Prime  string `protobuf:"bytes,2,opt,name=prime,proto3" json:"prime,omitempty"`
	Status bool   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DataForwardingStatus) Reset() {
	*x = DataForwardingStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_forwarding_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataForwardingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataForwardingStatus) ProtoMessage() {}

func (x *DataForwardingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_data_forwarding_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataForwardingStatus.ProtoReflect.Descriptor instead.
func (*DataForwardingStatus) Descriptor() ([]byte, []int) {
	return file_data_forwarding_proto_rawDescGZIP(), []int{5}
}

func (x *DataForwardingStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataForwardingStatus) GetPrime() string {
	if x != nil {
		return x.Prime
	}
	return ""
}

func (x *DataForwardingStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_data_forwarding_proto protoreflect.FileDescriptor

var file_data_forwarding_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x22, 0x43, 0x0a, 0x05, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x69, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x69, 0x74,
	0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x79, 0x61, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x22, 0x3e, 0x0a, 0x04, 0x42, 0x42, 0x6f, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x77, 0x12, 0x0c, 0x0a, 0x01, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x68, 0x22, 0x26, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79,
	0x22, 0xcf, 0x02, 0x0a, 0x04, 0x46, 0x61, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x62, 0x62, 0x6f,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x42, 0x6f, 0x78, 0x52, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x12,
	0x14, 0x0a, 0x05, 0x68, 0x61, 0x73, 0x48, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x68, 0x61, 0x73, 0x48, 0x50, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x41,
	0x6e, 0x67, 0x6c, 0x65, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x65,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x32, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x2e, 0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x22, 0x74, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x66, 0x61,
	0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x52, 0x05, 0x66, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61,
	0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x12,
	0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_forwarding_proto_rawDescOnce sync.Once
	file_data_forwarding_proto_rawDescData = file_data_forwarding_proto_rawDesc
)

func file_data_forwarding_proto_rawDescGZIP() []byte {
	file_data_forwarding_proto_rawDescOnce.Do(func() {
		file_data_forwarding_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_forwarding_proto_rawDescData)
	})
	return file_data_forwarding_proto_rawDescData
}

var file_data_forwarding_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_data_forwarding_proto_goTypes = []any{
	(*Angle)(nil),                // 0: forwarding.Angle
	(*BBox)(nil),                 // 1: forwarding.BBox
	(*Keypoint)(nil),             // 2: forwarding.Keypoint
	(*Face)(nil),                 // 3: forwarding.Face
	(*DataForwarding)(nil),       // 4: forwarding.DataForwarding
	(*DataForwardingStatus)(nil), // 5: forwarding.DataForwardingStatus
}
var file_data_forwarding_proto_depIdxs = []int32{
	1, // 0: forwarding.Face.bbox:type_name -> forwarding.BBox
	0, // 1: forwarding.Face.pose:type_name -> forwarding.Angle
	2, // 2: forwarding.Face.keypoints:type_name -> forwarding.Keypoint
	3, // 3: forwarding.DataForwarding.faces:type_name -> forwarding.Face
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_forwarding_proto_init() }
func file_data_forwarding_proto_init() {
	if File_data_forwarding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_forwarding_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Angle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_forwarding_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_forwarding_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Keypoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_forwarding_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Face); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_forwarding_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DataForwarding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_forwarding_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DataForwardingStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_forwarding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_forwarding_proto_goTypes,
		DependencyIndexes: file_data_forwarding_proto_depIdxs,
		MessageInfos:      file_data_forwarding_proto_msgTypes,
	}.Build()
	File_data_forwarding_proto = out.File
	file_data_forwarding_proto_rawDesc = nil
	file_data_forwarding_proto_goTypes = nil
	file_data_forwarding_proto_depIdxs = nil
}
