# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_processing_srv.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_processing_srv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import face_pb2 as face__pb2

from face_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64\x61ta_processing_srv.proto\x12\x17\x63om.interview.embedding\x1a\nface.proto\":\n\x13RegisterFaceRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x14\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x0b\x32\x05.Face\"\x16\n\x14RegisterFaceResponse\":\n\x13GetEmbeddingRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x14\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x0b\x32\x05.Face\",\n\x14GetEmbeddingResponse\x12\x14\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x05.Face2\xed\x01\n\x10\x45mbeddingService\x12i\n\x08Register\x12,.com.interview.embedding.RegisterFaceRequest\x1a-.com.interview.embedding.RegisterFaceResponse\"\x00\x12n\n\x0cGetEmbedding\x12-.com.interview.embedding.GetEmbeddingResponse\x1a-.com.interview.embedding.GetEmbeddingResponse\"\x00P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_processing_srv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERFACEREQUEST']._serialized_start=66
  _globals['_REGISTERFACEREQUEST']._serialized_end=124
  _globals['_REGISTERFACERESPONSE']._serialized_start=126
  _globals['_REGISTERFACERESPONSE']._serialized_end=148
  _globals['_GETEMBEDDINGREQUEST']._serialized_start=150
  _globals['_GETEMBEDDINGREQUEST']._serialized_end=208
  _globals['_GETEMBEDDINGRESPONSE']._serialized_start=210
  _globals['_GETEMBEDDINGRESPONSE']._serialized_end=254
  _globals['_EMBEDDINGSERVICE']._serialized_start=257
  _globals['_EMBEDDINGSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
