# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection_srv.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'detection_srv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import face_pb2 as face__pb2

from face_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x65tection_srv.proto\x12\x17\x63om.interview.detection\x1a\nface.proto\"\x17\n\x06\x43onfig\x12\r\n\x05hasHP\x18\x01 \x01(\x08\"Z\n\x18\x44\x65tectSingleImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12/\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1f.com.interview.detection.Config\"1\n\x19\x44\x65tectSingleImageResponse\x12\x14\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x05.Face\"V\n\x13\x44\x65tectImagesReqeust\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12/\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1f.com.interview.detection.Config\",\n\x14\x44\x65tectImagesResponse\x12\x14\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x05.Face2\xff\x01\n\x10\x44\x65tectionService\x12|\n\x11\x44\x65tectSingleImage\x12\x31.com.interview.detection.DetectSingleImageRequest\x1a\x32.com.interview.detection.DetectSingleImageResponse\"\x00\x12m\n\x0c\x44\x65tectImages\x12,.com.interview.detection.DetectImagesReqeust\x1a-.com.interview.detection.DetectImagesResponse\"\x00P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_srv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIG']._serialized_start=60
  _globals['_CONFIG']._serialized_end=83
  _globals['_DETECTSINGLEIMAGEREQUEST']._serialized_start=85
  _globals['_DETECTSINGLEIMAGEREQUEST']._serialized_end=175
  _globals['_DETECTSINGLEIMAGERESPONSE']._serialized_start=177
  _globals['_DETECTSINGLEIMAGERESPONSE']._serialized_end=226
  _globals['_DETECTIMAGESREQEUST']._serialized_start=228
  _globals['_DETECTIMAGESREQEUST']._serialized_end=314
  _globals['_DETECTIMAGESRESPONSE']._serialized_start=316
  _globals['_DETECTIMAGESRESPONSE']._serialized_end=360
  _globals['_DETECTIONSERVICE']._serialized_start=363
  _globals['_DETECTIONSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
