// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: face.sql

package sqlcmain

import (
	"context"
)

const createNewFace = `-- name: CreateNewFace :one
INSERT INTO "Face"(
   person_id,
   path
)VALUES (
$1, $2
) RETURNING id, person_id, path
`

func (q *Queries) CreateNewFace(ctx context.Context, personID int32, path string) (Face, error) {
	row := q.db.QueryRowContext(ctx, createNewFace, personID, path)
	var i Face
	err := row.Scan(&i.ID, &i.PersonID, &i.Path)
	return i, err
}
