// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcmain

import (
	"context"
)

type Querier interface {
	CreateNewFace(ctx context.Context, personID int32, path string) (Face, error)
	CreatePerson(ctx context.Context, prime string, firstName string, lastName string) (Person, error)
	GetPersonByPrime(ctx context.Context, prime string) (Person, error)
	GetPersonList(ctx context.Context, limit int32, offset int32) ([]Person, error)
}

var _ Querier = (*Queries)(nil)
