// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePerson(ctx context.Context, prime string, firstName string, lastName string) (Person, error)
	GetPersonList(ctx context.Context, limit int32, offset int32) ([]Person, error)
}

var _ Querier = (*Queries)(nil)
