version: '3'
networks:
  app-kyc:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.9.2'
    volumes:
      - ./storage/zookeeper-persistence:/bitnami/zookeeper
    ports:
      - '2181:2181'

    environment:
      - ZOO_SERVER_ID=1
      - ZOO_LOG_LEVEL=WARN
      - ALLOW_ANONYMOUS_LOGIN=yes

    networks:
      - app-kyc
    
  kafka:
    image: 'bitnami/kafka:3.7'
    volumes:
      - ./storage/kafka-persistence:/bitnami/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9094,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LOG4J_ROOT_LOGLEVEL=ERROR

    networks:
      - app-kyc
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:7.0
    environment:
      - REDIS_PASSWORD=lora123456
      - REDIS_IO_THREADS=2
      - REDIS_IO_THREADS_DO_READS=yes
      - REDIS_PORT_NUMBER=6379
    volumes:
      - ./storage/redis:/bitnami/redis/data

    ports:
      - "6379:6379"
