# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import detection_srv_pb2 as detection__srv__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in detection_srv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectSingleImage = channel.unary_unary(
                '/com.interview.detection.DetectionService/DetectSingleImage',
                request_serializer=detection__srv__pb2.DetectSingleImageRequest.SerializeToString,
                response_deserializer=detection__srv__pb2.DetectSingleImageResponse.FromString,
                _registered_method=True)
        self.DetectImages = channel.unary_unary(
                '/com.interview.detection.DetectionService/DetectImages',
                request_serializer=detection__srv__pb2.DetectImagesReqeust.SerializeToString,
                response_deserializer=detection__srv__pb2.DetectImagesResponse.FromString,
                _registered_method=True)


class DetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectSingleImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectSingleImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectSingleImage,
                    request_deserializer=detection__srv__pb2.DetectSingleImageRequest.FromString,
                    response_serializer=detection__srv__pb2.DetectSingleImageResponse.SerializeToString,
            ),
            'DetectImages': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectImages,
                    request_deserializer=detection__srv__pb2.DetectImagesReqeust.FromString,
                    response_serializer=detection__srv__pb2.DetectImagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.interview.detection.DetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.interview.detection.DetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectSingleImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.interview.detection.DetectionService/DetectSingleImage',
            detection__srv__pb2.DetectSingleImageRequest.SerializeToString,
            detection__srv__pb2.DetectSingleImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.interview.detection.DetectionService/DetectImages',
            detection__srv__pb2.DetectImagesReqeust.SerializeToString,
            detection__srv__pb2.DetectImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
