# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'face.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nface.proto\"1\n\x05\x41ngle\x12\r\n\x05pitch\x18\x01 \x01(\x02\x12\x0b\n\x03yaw\x18\x02 \x01(\x02\x12\x0c\n\x04roll\x18\x03 \x01(\x02\"2\n\x04\x42\x42ox\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x12\t\n\x01w\x18\x03 \x01(\x03\x12\t\n\x01h\x18\x04 \x01(\x03\" \n\x08Keypoint\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"\xa9\x01\n\x04\x46\x61\x63\x65\x12\x13\n\x04\x62\x62ox\x18\x01 \x01(\x0b\x32\x05.BBox\x12\r\n\x05hasHP\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x14\n\x04pose\x18\x04 \x01(\x0b\x32\x06.Angle\x12\x11\n\tembedding\x18\x05 \x03(\x02\x12\x10\n\x08track_id\x18\x06 \x01(\x03\x12\x11\n\tperson_id\x18\x07 \x01(\t\x12\x1c\n\tkeypoints\x18\x08 \x03(\x0b\x32\t.Keypointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANGLE']._serialized_start=14
  _globals['_ANGLE']._serialized_end=63
  _globals['_BBOX']._serialized_start=65
  _globals['_BBOX']._serialized_end=115
  _globals['_KEYPOINT']._serialized_start=117
  _globals['_KEYPOINT']._serialized_end=149
  _globals['_FACE']._serialized_start=152
  _globals['_FACE']._serialized_end=321
# @@protoc_insertion_point(module_scope)
